#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Tienda")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    partial void InsertArchivo(Archivo instance);
    partial void UpdateArchivo(Archivo instance);
    partial void DeleteArchivo(Archivo instance);
    partial void InsertConfiguracion(Configuracion instance);
    partial void UpdateConfiguracion(Configuracion instance);
    partial void DeleteConfiguracion(Configuracion instance);
    partial void InsertFoto(Foto instance);
    partial void UpdateFoto(Foto instance);
    partial void DeleteFoto(Foto instance);
    partial void InsertItem(Item instance);
    partial void UpdateItem(Item instance);
    partial void DeleteItem(Item instance);
    partial void InsertLink(Link instance);
    partial void UpdateLink(Link instance);
    partial void DeleteLink(Link instance);
    partial void InsertOpcion(Opcion instance);
    partial void UpdateOpcion(Opcion instance);
    partial void DeleteOpcion(Opcion instance);
    partial void InsertOpcion_Item(Opcion_Item instance);
    partial void UpdateOpcion_Item(Opcion_Item instance);
    partial void DeleteOpcion_Item(Opcion_Item instance);
    partial void InsertUsuarios(Usuarios instance);
    partial void UpdateUsuarios(Usuarios instance);
    partial void DeleteUsuarios(Usuarios instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["TiendaConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Archivo> Archivo
		{
			get
			{
				return this.GetTable<Archivo>();
			}
		}
		
		public System.Data.Linq.Table<Configuracion> Configuracion
		{
			get
			{
				return this.GetTable<Configuracion>();
			}
		}
		
		public System.Data.Linq.Table<Foto> Foto
		{
			get
			{
				return this.GetTable<Foto>();
			}
		}
		
		public System.Data.Linq.Table<Item> Item
		{
			get
			{
				return this.GetTable<Item>();
			}
		}
		
		public System.Data.Linq.Table<Link> Link
		{
			get
			{
				return this.GetTable<Link>();
			}
		}
		
		public System.Data.Linq.Table<Opcion> Opcion
		{
			get
			{
				return this.GetTable<Opcion>();
			}
		}
		
		public System.Data.Linq.Table<Opcion_Item> Opcion_Item
		{
			get
			{
				return this.GetTable<Opcion_Item>();
			}
		}
		
		public System.Data.Linq.Table<Usuarios> Usuarios
		{
			get
			{
				return this.GetTable<Usuarios>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Archivo")]
	public partial class Archivo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDArchivo;
		
		private System.DateTime _Modificado;
		
		private string _NombreArchivo;
		
		private System.Data.Linq.Binary _Contenido;
		
		private long _IDItem;
		
		private System.Nullable<long> _Orden;
		
		private string _Titulo;
		
		private EntityRef<Item> _Item;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDArchivoChanging(long value);
    partial void OnIDArchivoChanged();
    partial void OnModificadoChanging(System.DateTime value);
    partial void OnModificadoChanged();
    partial void OnNombreArchivoChanging(string value);
    partial void OnNombreArchivoChanged();
    partial void OnContenidoChanging(System.Data.Linq.Binary value);
    partial void OnContenidoChanged();
    partial void OnIDItemChanging(long value);
    partial void OnIDItemChanged();
    partial void OnOrdenChanging(System.Nullable<long> value);
    partial void OnOrdenChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    #endregion
		
		public Archivo()
		{
			this._Item = default(EntityRef<Item>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDArchivo", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDArchivo
		{
			get
			{
				return this._IDArchivo;
			}
			set
			{
				if ((this._IDArchivo != value))
				{
					this.OnIDArchivoChanging(value);
					this.SendPropertyChanging();
					this._IDArchivo = value;
					this.SendPropertyChanged("IDArchivo");
					this.OnIDArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modificado", DbType="DateTime NOT NULL")]
		public System.DateTime Modificado
		{
			get
			{
				return this._Modificado;
			}
			set
			{
				if ((this._Modificado != value))
				{
					this.OnModificadoChanging(value);
					this.SendPropertyChanging();
					this._Modificado = value;
					this.SendPropertyChanged("Modificado");
					this.OnModificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreArchivo", DbType="NVarChar(500)")]
		public string NombreArchivo
		{
			get
			{
				return this._NombreArchivo;
			}
			set
			{
				if ((this._NombreArchivo != value))
				{
					this.OnNombreArchivoChanging(value);
					this.SendPropertyChanging();
					this._NombreArchivo = value;
					this.SendPropertyChanged("NombreArchivo");
					this.OnNombreArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Contenido", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary Contenido
		{
			get
			{
				return this._Contenido;
			}
			set
			{
				if ((this._Contenido != value))
				{
					this.OnContenidoChanging(value);
					this.SendPropertyChanging();
					this._Contenido = value;
					this.SendPropertyChanged("Contenido");
					this.OnContenidoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDItem", DbType="BigInt NOT NULL")]
		public long IDItem
		{
			get
			{
				return this._IDItem;
			}
			set
			{
				if ((this._IDItem != value))
				{
					if (this._Item.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDItemChanging(value);
					this.SendPropertyChanging();
					this._IDItem = value;
					this.SendPropertyChanged("IDItem");
					this.OnIDItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="BigInt")]
		public System.Nullable<long> Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(200)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Archivo", Storage="_Item", ThisKey="IDItem", OtherKey="IDItem", IsForeignKey=true)]
		public Item Item
		{
			get
			{
				return this._Item.Entity;
			}
			set
			{
				Item previousValue = this._Item.Entity;
				if (((previousValue != value) 
							|| (this._Item.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Item.Entity = null;
						previousValue.Archivo.Remove(this);
					}
					this._Item.Entity = value;
					if ((value != null))
					{
						value.Archivo.Add(this);
						this._IDItem = value.IDItem;
					}
					else
					{
						this._IDItem = default(long);
					}
					this.SendPropertyChanged("Item");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Configuracion")]
	public partial class Configuracion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Nombre;
		
		private string _Valor;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnValorChanging(string value);
    partial void OnValorChanged();
    #endregion
		
		public Configuracion()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Valor", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Valor
		{
			get
			{
				return this._Valor;
			}
			set
			{
				if ((this._Valor != value))
				{
					this.OnValorChanging(value);
					this.SendPropertyChanging();
					this._Valor = value;
					this.SendPropertyChanged("Valor");
					this.OnValorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Foto")]
	public partial class Foto : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDFoto;
		
		private System.DateTime _Modificado;
		
		private string _NombreArchivo;
		
		private bool _EsFotoPrincipal;
		
		private System.Data.Linq.Binary _ContenidoBinarioImagenGrande;
		
		private System.Data.Linq.Binary _ContenidoBinarioImagenChica;
		
		private long _IDItem;
		
		private System.Nullable<long> _Orden;
		
		private string _Titulo;
		
		private EntityRef<Item> _Item;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDFotoChanging(long value);
    partial void OnIDFotoChanged();
    partial void OnModificadoChanging(System.DateTime value);
    partial void OnModificadoChanged();
    partial void OnNombreArchivoChanging(string value);
    partial void OnNombreArchivoChanged();
    partial void OnEsFotoPrincipalChanging(bool value);
    partial void OnEsFotoPrincipalChanged();
    partial void OnContenidoBinarioImagenGrandeChanging(System.Data.Linq.Binary value);
    partial void OnContenidoBinarioImagenGrandeChanged();
    partial void OnContenidoBinarioImagenChicaChanging(System.Data.Linq.Binary value);
    partial void OnContenidoBinarioImagenChicaChanged();
    partial void OnIDItemChanging(long value);
    partial void OnIDItemChanged();
    partial void OnOrdenChanging(System.Nullable<long> value);
    partial void OnOrdenChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    #endregion
		
		public Foto()
		{
			this._Item = default(EntityRef<Item>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDFoto", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDFoto
		{
			get
			{
				return this._IDFoto;
			}
			set
			{
				if ((this._IDFoto != value))
				{
					this.OnIDFotoChanging(value);
					this.SendPropertyChanging();
					this._IDFoto = value;
					this.SendPropertyChanged("IDFoto");
					this.OnIDFotoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Modificado", DbType="DateTime NOT NULL")]
		public System.DateTime Modificado
		{
			get
			{
				return this._Modificado;
			}
			set
			{
				if ((this._Modificado != value))
				{
					this.OnModificadoChanging(value);
					this.SendPropertyChanging();
					this._Modificado = value;
					this.SendPropertyChanged("Modificado");
					this.OnModificadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreArchivo", DbType="NVarChar(500)")]
		public string NombreArchivo
		{
			get
			{
				return this._NombreArchivo;
			}
			set
			{
				if ((this._NombreArchivo != value))
				{
					this.OnNombreArchivoChanging(value);
					this.SendPropertyChanging();
					this._NombreArchivo = value;
					this.SendPropertyChanged("NombreArchivo");
					this.OnNombreArchivoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EsFotoPrincipal", DbType="Bit NOT NULL")]
		public bool EsFotoPrincipal
		{
			get
			{
				return this._EsFotoPrincipal;
			}
			set
			{
				if ((this._EsFotoPrincipal != value))
				{
					this.OnEsFotoPrincipalChanging(value);
					this.SendPropertyChanging();
					this._EsFotoPrincipal = value;
					this.SendPropertyChanged("EsFotoPrincipal");
					this.OnEsFotoPrincipalChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContenidoBinarioImagenGrande", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ContenidoBinarioImagenGrande
		{
			get
			{
				return this._ContenidoBinarioImagenGrande;
			}
			set
			{
				if ((this._ContenidoBinarioImagenGrande != value))
				{
					this.OnContenidoBinarioImagenGrandeChanging(value);
					this.SendPropertyChanging();
					this._ContenidoBinarioImagenGrande = value;
					this.SendPropertyChanged("ContenidoBinarioImagenGrande");
					this.OnContenidoBinarioImagenGrandeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ContenidoBinarioImagenChica", DbType="Image", UpdateCheck=UpdateCheck.Never)]
		public System.Data.Linq.Binary ContenidoBinarioImagenChica
		{
			get
			{
				return this._ContenidoBinarioImagenChica;
			}
			set
			{
				if ((this._ContenidoBinarioImagenChica != value))
				{
					this.OnContenidoBinarioImagenChicaChanging(value);
					this.SendPropertyChanging();
					this._ContenidoBinarioImagenChica = value;
					this.SendPropertyChanged("ContenidoBinarioImagenChica");
					this.OnContenidoBinarioImagenChicaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDItem", DbType="BigInt NOT NULL")]
		public long IDItem
		{
			get
			{
				return this._IDItem;
			}
			set
			{
				if ((this._IDItem != value))
				{
					if (this._Item.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDItemChanging(value);
					this.SendPropertyChanging();
					this._IDItem = value;
					this.SendPropertyChanged("IDItem");
					this.OnIDItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="BigInt")]
		public System.Nullable<long> Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(200)")]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Foto", Storage="_Item", ThisKey="IDItem", OtherKey="IDItem", IsForeignKey=true)]
		public Item Item
		{
			get
			{
				return this._Item.Entity;
			}
			set
			{
				Item previousValue = this._Item.Entity;
				if (((previousValue != value) 
							|| (this._Item.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Item.Entity = null;
						previousValue.Foto.Remove(this);
					}
					this._Item.Entity = value;
					if ((value != null))
					{
						value.Foto.Add(this);
						this._IDItem = value.IDItem;
					}
					else
					{
						this._IDItem = default(long);
					}
					this.SendPropertyChanged("Item");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Item")]
	public partial class Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDItem;
		
		private System.DateTime _FechaCreacion;
		
		private bool _Recomendado;
		
		private bool _Publicado;
		
		private bool _LoNuevo;
		
		private string _Codigo;
		
		private string _Titulo;
		
		private string _Descripcion;
		
		private string _PalabrasClave;
		
		private string _Grupo;
		
		private string _SubGrupo;
		
		private string _Marca;
		
		private long _Orden;
		
		private decimal _Precio;
		
		private EntitySet<Archivo> _Archivo;
		
		private EntitySet<Foto> _Foto;
		
		private EntitySet<Link> _Link;
		
		private EntitySet<Opcion_Item> _Opcion_Item;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDItemChanging(long value);
    partial void OnIDItemChanged();
    partial void OnFechaCreacionChanging(System.DateTime value);
    partial void OnFechaCreacionChanged();
    partial void OnRecomendadoChanging(bool value);
    partial void OnRecomendadoChanged();
    partial void OnPublicadoChanging(bool value);
    partial void OnPublicadoChanged();
    partial void OnLoNuevoChanging(bool value);
    partial void OnLoNuevoChanged();
    partial void OnCodigoChanging(string value);
    partial void OnCodigoChanged();
    partial void OnTituloChanging(string value);
    partial void OnTituloChanged();
    partial void OnDescripcionChanging(string value);
    partial void OnDescripcionChanged();
    partial void OnPalabrasClaveChanging(string value);
    partial void OnPalabrasClaveChanged();
    partial void OnGrupoChanging(string value);
    partial void OnGrupoChanged();
    partial void OnSubGrupoChanging(string value);
    partial void OnSubGrupoChanged();
    partial void OnMarcaChanging(string value);
    partial void OnMarcaChanged();
    partial void OnOrdenChanging(long value);
    partial void OnOrdenChanged();
    partial void OnPrecioChanging(decimal value);
    partial void OnPrecioChanged();
    #endregion
		
		public Item()
		{
			this._Archivo = new EntitySet<Archivo>(new Action<Archivo>(this.attach_Archivo), new Action<Archivo>(this.detach_Archivo));
			this._Foto = new EntitySet<Foto>(new Action<Foto>(this.attach_Foto), new Action<Foto>(this.detach_Foto));
			this._Link = new EntitySet<Link>(new Action<Link>(this.attach_Link), new Action<Link>(this.detach_Link));
			this._Opcion_Item = new EntitySet<Opcion_Item>(new Action<Opcion_Item>(this.attach_Opcion_Item), new Action<Opcion_Item>(this.detach_Opcion_Item));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDItem", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDItem
		{
			get
			{
				return this._IDItem;
			}
			set
			{
				if ((this._IDItem != value))
				{
					this.OnIDItemChanging(value);
					this.SendPropertyChanging();
					this._IDItem = value;
					this.SendPropertyChanged("IDItem");
					this.OnIDItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FechaCreacion", DbType="DateTime NOT NULL")]
		public System.DateTime FechaCreacion
		{
			get
			{
				return this._FechaCreacion;
			}
			set
			{
				if ((this._FechaCreacion != value))
				{
					this.OnFechaCreacionChanging(value);
					this.SendPropertyChanging();
					this._FechaCreacion = value;
					this.SendPropertyChanged("FechaCreacion");
					this.OnFechaCreacionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Recomendado", DbType="Bit NOT NULL")]
		public bool Recomendado
		{
			get
			{
				return this._Recomendado;
			}
			set
			{
				if ((this._Recomendado != value))
				{
					this.OnRecomendadoChanging(value);
					this.SendPropertyChanging();
					this._Recomendado = value;
					this.SendPropertyChanged("Recomendado");
					this.OnRecomendadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Publicado", DbType="Bit NOT NULL")]
		public bool Publicado
		{
			get
			{
				return this._Publicado;
			}
			set
			{
				if ((this._Publicado != value))
				{
					this.OnPublicadoChanging(value);
					this.SendPropertyChanging();
					this._Publicado = value;
					this.SendPropertyChanged("Publicado");
					this.OnPublicadoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoNuevo", DbType="Bit NOT NULL")]
		public bool LoNuevo
		{
			get
			{
				return this._LoNuevo;
			}
			set
			{
				if ((this._LoNuevo != value))
				{
					this.OnLoNuevoChanging(value);
					this.SendPropertyChanging();
					this._LoNuevo = value;
					this.SendPropertyChanged("LoNuevo");
					this.OnLoNuevoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Codigo", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Codigo
		{
			get
			{
				return this._Codigo;
			}
			set
			{
				if ((this._Codigo != value))
				{
					this.OnCodigoChanging(value);
					this.SendPropertyChanging();
					this._Codigo = value;
					this.SendPropertyChanged("Codigo");
					this.OnCodigoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Titulo", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Titulo
		{
			get
			{
				return this._Titulo;
			}
			set
			{
				if ((this._Titulo != value))
				{
					this.OnTituloChanging(value);
					this.SendPropertyChanging();
					this._Titulo = value;
					this.SendPropertyChanged("Titulo");
					this.OnTituloChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Descripcion", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string Descripcion
		{
			get
			{
				return this._Descripcion;
			}
			set
			{
				if ((this._Descripcion != value))
				{
					this.OnDescripcionChanging(value);
					this.SendPropertyChanging();
					this._Descripcion = value;
					this.SendPropertyChanged("Descripcion");
					this.OnDescripcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PalabrasClave", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
		public string PalabrasClave
		{
			get
			{
				return this._PalabrasClave;
			}
			set
			{
				if ((this._PalabrasClave != value))
				{
					this.OnPalabrasClaveChanging(value);
					this.SendPropertyChanging();
					this._PalabrasClave = value;
					this.SendPropertyChanged("PalabrasClave");
					this.OnPalabrasClaveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Grupo", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Grupo
		{
			get
			{
				return this._Grupo;
			}
			set
			{
				if ((this._Grupo != value))
				{
					this.OnGrupoChanging(value);
					this.SendPropertyChanging();
					this._Grupo = value;
					this.SendPropertyChanged("Grupo");
					this.OnGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SubGrupo", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string SubGrupo
		{
			get
			{
				return this._SubGrupo;
			}
			set
			{
				if ((this._SubGrupo != value))
				{
					this.OnSubGrupoChanging(value);
					this.SendPropertyChanging();
					this._SubGrupo = value;
					this.SendPropertyChanged("SubGrupo");
					this.OnSubGrupoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marca", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Marca
		{
			get
			{
				return this._Marca;
			}
			set
			{
				if ((this._Marca != value))
				{
					this.OnMarcaChanging(value);
					this.SendPropertyChanging();
					this._Marca = value;
					this.SendPropertyChanged("Marca");
					this.OnMarcaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Orden", DbType="BigInt NOT NULL")]
		public long Orden
		{
			get
			{
				return this._Orden;
			}
			set
			{
				if ((this._Orden != value))
				{
					this.OnOrdenChanging(value);
					this.SendPropertyChanging();
					this._Orden = value;
					this.SendPropertyChanged("Orden");
					this.OnOrdenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Precio", DbType="Money NOT NULL")]
		public decimal Precio
		{
			get
			{
				return this._Precio;
			}
			set
			{
				if ((this._Precio != value))
				{
					this.OnPrecioChanging(value);
					this.SendPropertyChanging();
					this._Precio = value;
					this.SendPropertyChanged("Precio");
					this.OnPrecioChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Archivo", Storage="_Archivo", ThisKey="IDItem", OtherKey="IDItem")]
		public EntitySet<Archivo> Archivo
		{
			get
			{
				return this._Archivo;
			}
			set
			{
				this._Archivo.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Foto", Storage="_Foto", ThisKey="IDItem", OtherKey="IDItem")]
		public EntitySet<Foto> Foto
		{
			get
			{
				return this._Foto;
			}
			set
			{
				this._Foto.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Link", Storage="_Link", ThisKey="IDItem", OtherKey="IDItem")]
		public EntitySet<Link> Link
		{
			get
			{
				return this._Link;
			}
			set
			{
				this._Link.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Opcion_Item", Storage="_Opcion_Item", ThisKey="IDItem", OtherKey="IDItem")]
		public EntitySet<Opcion_Item> Opcion_Item
		{
			get
			{
				return this._Opcion_Item;
			}
			set
			{
				this._Opcion_Item.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Archivo(Archivo entity)
		{
			this.SendPropertyChanging();
			entity.Item = this;
		}
		
		private void detach_Archivo(Archivo entity)
		{
			this.SendPropertyChanging();
			entity.Item = null;
		}
		
		private void attach_Foto(Foto entity)
		{
			this.SendPropertyChanging();
			entity.Item = this;
		}
		
		private void detach_Foto(Foto entity)
		{
			this.SendPropertyChanging();
			entity.Item = null;
		}
		
		private void attach_Link(Link entity)
		{
			this.SendPropertyChanging();
			entity.Item = this;
		}
		
		private void detach_Link(Link entity)
		{
			this.SendPropertyChanging();
			entity.Item = null;
		}
		
		private void attach_Opcion_Item(Opcion_Item entity)
		{
			this.SendPropertyChanging();
			entity.Item = this;
		}
		
		private void detach_Opcion_Item(Opcion_Item entity)
		{
			this.SendPropertyChanging();
			entity.Item = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Link")]
	public partial class Link : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDLink;
		
		private string _Nombre;
		
		private string _URL;
		
		private long _IDItem;
		
		private EntityRef<Item> _Item;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDLinkChanging(long value);
    partial void OnIDLinkChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnURLChanging(string value);
    partial void OnURLChanged();
    partial void OnIDItemChanging(long value);
    partial void OnIDItemChanged();
    #endregion
		
		public Link()
		{
			this._Item = default(EntityRef<Item>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLink", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDLink
		{
			get
			{
				return this._IDLink;
			}
			set
			{
				if ((this._IDLink != value))
				{
					this.OnIDLinkChanging(value);
					this.SendPropertyChanging();
					this._IDLink = value;
					this.SendPropertyChanged("IDLink");
					this.OnIDLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_URL", DbType="NVarChar(500) NOT NULL", CanBeNull=false)]
		public string URL
		{
			get
			{
				return this._URL;
			}
			set
			{
				if ((this._URL != value))
				{
					this.OnURLChanging(value);
					this.SendPropertyChanging();
					this._URL = value;
					this.SendPropertyChanged("URL");
					this.OnURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDItem", DbType="BigInt NOT NULL")]
		public long IDItem
		{
			get
			{
				return this._IDItem;
			}
			set
			{
				if ((this._IDItem != value))
				{
					if (this._Item.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDItemChanging(value);
					this.SendPropertyChanging();
					this._IDItem = value;
					this.SendPropertyChanged("IDItem");
					this.OnIDItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Link", Storage="_Item", ThisKey="IDItem", OtherKey="IDItem", IsForeignKey=true)]
		public Item Item
		{
			get
			{
				return this._Item.Entity;
			}
			set
			{
				Item previousValue = this._Item.Entity;
				if (((previousValue != value) 
							|| (this._Item.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Item.Entity = null;
						previousValue.Link.Remove(this);
					}
					this._Item.Entity = value;
					if ((value != null))
					{
						value.Link.Add(this);
						this._IDItem = value.IDItem;
					}
					else
					{
						this._IDItem = default(long);
					}
					this.SendPropertyChanged("Item");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Opcion")]
	public partial class Opcion : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDOpcion;
		
		private string _NombreOpcion;
		
		private string _GrupoOpcion;
		
		private EntitySet<Opcion_Item> _Opcion_Item;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDOpcionChanging(long value);
    partial void OnIDOpcionChanged();
    partial void OnNombreOpcionChanging(string value);
    partial void OnNombreOpcionChanged();
    partial void OnGrupoOpcionChanging(string value);
    partial void OnGrupoOpcionChanged();
    #endregion
		
		public Opcion()
		{
			this._Opcion_Item = new EntitySet<Opcion_Item>(new Action<Opcion_Item>(this.attach_Opcion_Item), new Action<Opcion_Item>(this.detach_Opcion_Item));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOpcion", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long IDOpcion
		{
			get
			{
				return this._IDOpcion;
			}
			set
			{
				if ((this._IDOpcion != value))
				{
					this.OnIDOpcionChanging(value);
					this.SendPropertyChanging();
					this._IDOpcion = value;
					this.SendPropertyChanged("IDOpcion");
					this.OnIDOpcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NombreOpcion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string NombreOpcion
		{
			get
			{
				return this._NombreOpcion;
			}
			set
			{
				if ((this._NombreOpcion != value))
				{
					this.OnNombreOpcionChanging(value);
					this.SendPropertyChanging();
					this._NombreOpcion = value;
					this.SendPropertyChanged("NombreOpcion");
					this.OnNombreOpcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GrupoOpcion", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string GrupoOpcion
		{
			get
			{
				return this._GrupoOpcion;
			}
			set
			{
				if ((this._GrupoOpcion != value))
				{
					this.OnGrupoOpcionChanging(value);
					this.SendPropertyChanging();
					this._GrupoOpcion = value;
					this.SendPropertyChanged("GrupoOpcion");
					this.OnGrupoOpcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Opcion_Opcion_Item", Storage="_Opcion_Item", ThisKey="IDOpcion", OtherKey="IDOpcion")]
		public EntitySet<Opcion_Item> Opcion_Item
		{
			get
			{
				return this._Opcion_Item;
			}
			set
			{
				this._Opcion_Item.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Opcion_Item(Opcion_Item entity)
		{
			this.SendPropertyChanging();
			entity.Opcion = this;
		}
		
		private void detach_Opcion_Item(Opcion_Item entity)
		{
			this.SendPropertyChanging();
			entity.Opcion = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Opcion_Item")]
	public partial class Opcion_Item : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _IDOpcion;
		
		private long _IDItem;
		
		private EntityRef<Item> _Item;
		
		private EntityRef<Opcion> _Opcion;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDOpcionChanging(long value);
    partial void OnIDOpcionChanged();
    partial void OnIDItemChanging(long value);
    partial void OnIDItemChanged();
    #endregion
		
		public Opcion_Item()
		{
			this._Item = default(EntityRef<Item>);
			this._Opcion = default(EntityRef<Opcion>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDOpcion", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDOpcion
		{
			get
			{
				return this._IDOpcion;
			}
			set
			{
				if ((this._IDOpcion != value))
				{
					if (this._Opcion.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDOpcionChanging(value);
					this.SendPropertyChanging();
					this._IDOpcion = value;
					this.SendPropertyChanged("IDOpcion");
					this.OnIDOpcionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDItem", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long IDItem
		{
			get
			{
				return this._IDItem;
			}
			set
			{
				if ((this._IDItem != value))
				{
					if (this._Item.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDItemChanging(value);
					this.SendPropertyChanging();
					this._IDItem = value;
					this.SendPropertyChanged("IDItem");
					this.OnIDItemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Item_Opcion_Item", Storage="_Item", ThisKey="IDItem", OtherKey="IDItem", IsForeignKey=true)]
		public Item Item
		{
			get
			{
				return this._Item.Entity;
			}
			set
			{
				Item previousValue = this._Item.Entity;
				if (((previousValue != value) 
							|| (this._Item.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Item.Entity = null;
						previousValue.Opcion_Item.Remove(this);
					}
					this._Item.Entity = value;
					if ((value != null))
					{
						value.Opcion_Item.Add(this);
						this._IDItem = value.IDItem;
					}
					else
					{
						this._IDItem = default(long);
					}
					this.SendPropertyChanged("Item");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Opcion_Opcion_Item", Storage="_Opcion", ThisKey="IDOpcion", OtherKey="IDOpcion", IsForeignKey=true)]
		public Opcion Opcion
		{
			get
			{
				return this._Opcion.Entity;
			}
			set
			{
				Opcion previousValue = this._Opcion.Entity;
				if (((previousValue != value) 
							|| (this._Opcion.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Opcion.Entity = null;
						previousValue.Opcion_Item.Remove(this);
					}
					this._Opcion.Entity = value;
					if ((value != null))
					{
						value.Opcion_Item.Add(this);
						this._IDOpcion = value.IDOpcion;
					}
					else
					{
						this._IDOpcion = default(long);
					}
					this.SendPropertyChanged("Opcion");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Usuarios")]
	public partial class Usuarios : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LoginID;
		
		private string _Password;
		
		private string _Nombre;
		
		private string _Email;
		
		private bool _Administrador;
		
    #region Definiciones de métodos de extensibilidad
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLoginIDChanging(string value);
    partial void OnLoginIDChanged();
    partial void OnPasswordChanging(string value);
    partial void OnPasswordChanged();
    partial void OnNombreChanging(string value);
    partial void OnNombreChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnAdministradorChanging(bool value);
    partial void OnAdministradorChanged();
    #endregion
		
		public Usuarios()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LoginID", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LoginID
		{
			get
			{
				return this._LoginID;
			}
			set
			{
				if ((this._LoginID != value))
				{
					this.OnLoginIDChanging(value);
					this.SendPropertyChanging();
					this._LoginID = value;
					this.SendPropertyChanged("LoginID");
					this.OnLoginIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Password", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get
			{
				return this._Password;
			}
			set
			{
				if ((this._Password != value))
				{
					this.OnPasswordChanging(value);
					this.SendPropertyChanging();
					this._Password = value;
					this.SendPropertyChanged("Password");
					this.OnPasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nombre", DbType="NVarChar(200)")]
		public string Nombre
		{
			get
			{
				return this._Nombre;
			}
			set
			{
				if ((this._Nombre != value))
				{
					this.OnNombreChanging(value);
					this.SendPropertyChanging();
					this._Nombre = value;
					this.SendPropertyChanged("Nombre");
					this.OnNombreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="NVarChar(500)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Administrador", DbType="Bit NOT NULL")]
		public bool Administrador
		{
			get
			{
				return this._Administrador;
			}
			set
			{
				if ((this._Administrador != value))
				{
					this.OnAdministradorChanging(value);
					this.SendPropertyChanging();
					this._Administrador = value;
					this.SendPropertyChanged("Administrador");
					this.OnAdministradorChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
